apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-app.fullname" . }}
  labels:
    {{- include "user-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "user-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "user-app.serviceAccountName" . }}
      {{- if .Values.podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  {{- include "user-app.selectorLabels" . | nindent 18 }}
              topologyKey: topology.kubernetes.io/zone
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: TABLE_NAME
              value: {{ .Values.env.TABLE_NAME | quote }}
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: APP_BASE_PATH
              value: {{ printf "/%s" .Values.ingress.basePath | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
